-- MySQL Script generated by MySQL Workbench
-- Tue Jun 27 17:16:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema factorygame
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `factorygame` ;

-- -----------------------------------------------------
-- Schema factorygame
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `factorygame` DEFAULT CHARACTER SET utf8 ;
USE `factorygame` ;

-- -----------------------------------------------------
-- Table `factorygame`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `factorygame`.`users` ;

CREATE TABLE IF NOT EXISTS `factorygame`.`users` (
  `id` VARCHAR(50) ,
  `UserName` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `factorygame`.`profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `factorygame`.`profile` ;

CREATE TABLE IF NOT EXISTS `factorygame`.`profile` (
  `id` INT(11) NOT NULL,
  `SaveName` VARCHAR(225) NOT NULL,
  `users_id` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  UNIQUE INDEX `ID_UNIQUE` (`id` ASC) ,
  INDEX `fk_savefile_users_idx` (`users_id` ASC) ,
  CONSTRAINT `fk_savefile_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `factorygame`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `factorygame`.`map`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `factorygame`.`map` ;

CREATE TABLE IF NOT EXISTS `factorygame`.`map` (
  `xRange` FLOAT NOT NULL,
  `yRange` FLOAT NOT NULL,
  `profile_id` INT(11) NOT NULL,
  PRIMARY KEY (`profile_id`),
  INDEX `fk_map_savefile1_idx` (`profile_id` ASC) ,
  CONSTRAINT `fk_map_savefile1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `factorygame`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `factorygame`.`statistics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `factorygame`.`statistics` ;

CREATE TABLE IF NOT EXISTS `factorygame`.`statistics` (
  `DateMade` DATETIME NOT NULL,
  `DateSeen` DATETIME NULL DEFAULT NULL,
  `TimePlayed` VARCHAR(45) NULL DEFAULT NULL,
  `profile_id` INT(11) NOT NULL,
  `Money` INT NULL,
  PRIMARY KEY (`profile_id`),
  CONSTRAINT `fk__savefile1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `factorygame`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `factorygame`.`objects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `factorygame`.`objects` ;

CREATE TABLE IF NOT EXISTS `factorygame`.`objects` (
  `position_x` INT NOT NULL,
  `position_y` INT NOT NULL,
  `objectOrder` VARCHAR(45) NOT NULL,
  `profile_id` INT(11) NOT NULL,
  PRIMARY KEY (`position_x`, `position_y`, `profile_id`),
  INDEX `fk_objects_map1_idx` (`profile_id` ASC) ,
  CONSTRAINT `fk_objects_map1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `factorygame`.`map` (`profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;