-- MySQL Script generated by MySQL Workbench
-- Tue Jun 27 01:27:48 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema factorygame
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `factorygame` ;

-- -----------------------------------------------------
-- Schema factorygame
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `factorygame` DEFAULT CHARACTER SET utf8 ;
USE `factorygame` ;

-- -----------------------------------------------------
-- Table `factorygame`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `factorygame`.`users` ;

CREATE TABLE IF NOT EXISTS `factorygame`.`users` (
  `UserId` VARCHAR(50),
  `UserName` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`UserId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `factorygame`.`savefile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `factorygame`.`savefile` ;

CREATE TABLE IF NOT EXISTS `factorygame`.`savefile` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `SaveName` VARCHAR(225) NOT NULL,
  `users_UserId` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`, `users_UserId`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `fk_savefile_users_idx` (`users_UserId` ASC),
  CONSTRAINT `fk_savefile_users`
    FOREIGN KEY (`users_UserId`)
    REFERENCES `factorygame`.`users` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `factorygame`.`map`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `factorygame`.`map` ;

CREATE TABLE IF NOT EXISTS `factorygame`.`map` (
  `xRange` FLOAT NOT NULL,
  `yRange` FLOAT NOT NULL,
  `savefile_ID` INT(11) NOT NULL,
  PRIMARY KEY (`savefile_ID`),
  INDEX `fk_map_savefile1_idx` (`savefile_ID` ASC),
  CONSTRAINT `fk_map_savefile1`
    FOREIGN KEY (`savefile_ID`)
    REFERENCES `factorygame`.`savefile` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `factorygame`.`profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `factorygame`.`profile` ;

CREATE TABLE IF NOT EXISTS `factorygame`.`profile` (
  `DateMade` DATETIME NOT NULL,
  `DateSeen` DATETIME NULL DEFAULT NULL,
  `TimePlayed` VARCHAR(45) NULL DEFAULT NULL,
  `savefile_ID` INT(11) NOT NULL,
  `Money` INT NULL,
  PRIMARY KEY (`savefile_ID`),
  CONSTRAINT `fk__savefile1`
    FOREIGN KEY (`savefile_ID`)
    REFERENCES `factorygame`.`savefile` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `factorygame`.`objects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `factorygame`.`objects` ;

CREATE TABLE IF NOT EXISTS `factorygame`.`objects` (
  `position_x` INT NOT NULL,
  `position_y` INT NOT NULL,
  `objectOrder` VARCHAR(45) NOT NULL,
  `map_savefile_ID` INT(11) NOT NULL,
  PRIMARY KEY (`position_x`, `position_y`, `map_savefile_ID`),
  INDEX `fk_objects_map1_idx` (`map_savefile_ID` ASC),
  CONSTRAINT `fk_objects_map1`
    FOREIGN KEY (`map_savefile_ID`)
    REFERENCES `factorygame`.`map` (`savefile_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

